using System.Collections.Generic;

namespace QuizGame.AllQuizzes.MiscellaneousQuizzes
{
    public class GeneralKnowledge
    {
        // TODO: Implement explanation after answering each question if possible using structure
        public List<string> questionsList = new List<string>()
        {
            "What country is sushi from?",
            "According to the Old Testament, how many days did it take God to create the world?",
            "Which is the world's most populous country?",
            "About what percentage of the earth's surface is water?",
            "Is Washington, D.C. a state?",
            "When should you take antibiotics?",
            "Is is true that the shape of a pregnant belly can help parents predict the sex of their baby?",
            "Is Africa a country?",
            "Why are French, Spanish and Italian called Romance languages?",
            "How many moons does the earth have?",
            "About how many countries are there in the world?",
            "Is cancer usually contagious?",
            "Which of these is not a major world ocean?",
            "What is the official language of the U.S.?",
            "Is is true that only very pale people need to wear sunscreen?",
            "Can you drink ocean water?",
            "How many planets are there in the solar system?",
            "Is the death penalty legal in all U.S. states?",
            "Where is the country of Egypt?",
            "The Koran is the holy book of which religion?",
            "Can most adults digest milk?",
            "Is is true that it is more dangerous to fly on a plane than drive?", // answer contradicts on website because it says its more dangerous to drive in the comments, but the answer is asking if its more dangerous to fly, and no should be corrrect, as it is NOT safer than driving
            "Which of these rivers is often cited as the longest river on earth?",
            "If a religion is polytheistic, it has:",
            "Which of these things causes autism?",
            "Most of the world's ______ occur in the area known as the Pacific Ring of Fire.",
            "Which is the world's largest desert?",
            "Do sharks commonly eat people?",
            "Which of these languages is English most closely related to?",
            "What country does yoga come from?",
            "Which of these countries is not a part of Scandinavia?",
            "Which of these foods is most common in the standard Western diet?",
            "Which country is shaped like a boot?",
            "Is Puerto Rico a part of the U.S.?",
            "What percentage of the world's population has red hair?",
        };

        public List<string> answerListCorrect = new List<string>()
        {
            "Japan",
            "6",
            "China",
            "70%",
            "No",
            "For bacterial infections",
            "No",
            "No",
            "They have roots in Latin, which was spoken by Romans.",
            "1",
            "200",
            "No",
            "American",
            "There isn't one",
            "No",
            "No",
            "8",
            "No",
            "Africa",
            "Islam",
            "No",
            "No",
            "Nile",
            "Multiple gods",
            "Genetic factors",
            "Earthquakes",
            "Sahara",
            "No",
            "German",
            "India",
            "Netherlands",
            "Red meat",
            "Italy",
            "Yes",
            "About 2%",
        };

        // make this list the list that remains when hint is activated(makes the second or third most sense)
        public List<string> answerListIncorrect1 = new List<string>()
        {
            "Thailand",
            "7",
            "America",
            "90%",
            "Yes",
            "For viruses",
            "Yes",
            "Yes",
            "They sound romantic",
            "0",
            "50",
            "Yes",
            "Indian",
            "English",
            "Yes",
            "Yes",
            "9",
            "Yes",
            "South America",
            "Christianity",
            "Yes",
            "Yes",
            "Delaware",
            "1 God",
            "Vaccines",
            "Droughts",
            "Gobi",
            "Yes",
            "Russian",
            "Japan",
            "Norway",
            "Fish",
            "Canada",
            "No",
            "10%",
        };
        public List<string> answerListIncorrect2 = new List<string>()
        {
            "India",
            "6",
            "Brazil",
            "10%",
            string.Empty,
            "Whenever you feel sick",
            string.Empty,
            string.Empty,
            "They are only spoken by Romani",
            "5",
            "100",
            string.Empty,
            "Arctic",
            "Spanish",
            string.Empty,
            string.Empty,
            "2",
            string.Empty,
            "Asia",
            "Hinduism",
            string.Empty,
            string.Empty,
            "Ganges",
            "Martyrs",
            "The common cold",
            "Floods",
            "Mojave",
            string.Empty,
            "Gujrati",
            "Canada",
            "Sweden",
            "Vegetables",
            "Qatar",
            string.Empty,
            "0%",
        };
        public List<string> answerListIncorrect3 = new List<string>()
        {
            "France",
            "1",
            "India",
            "50%",
            string.Empty,
            "Never!, it is highly toxic, and can cause grevious damage to human tissue",
            string.Empty,
            string.Empty,
            "They were spread by those who roam",
            "2",
            "400",
            string.Empty,
            "Pacific",
            "Latin",
            string.Empty,
            string.Empty,
            "11",
            string.Empty,
            "Europe",
            "Judism",
            string.Empty,
            string.Empty,
            "Yamuna",
            "Angels",
            "Eating spicy food",
            "Tornadoes",
            "Thar",
            string.Empty,
            "Spanish",
            "Guatamala",
            "Denmark",
            "Fruit",
            "Canada",
            string.Empty,
            "About 25%",
        };
    }
}
